dist: xenial
language: java
jdk:
  -openjdk8
services:
  - docker

before_install:
  - ./.travis/install_groovy.sh
  - docker pull postgres:latest
  - docker pull jumpmind/symmetricds:latest

script:
  - cd run
  - ./showcp.groovy
